module: ResponseTime
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-ResponseTime/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, ResponseTime.xcodeproj, -target, ResponseTime, -toolchain, org.swift.30201600907a, LIBRARY_SEARCH_PATHS=.build/debug]

